# Top-Rated Movies Pipeline Configuration

# TMDB API Configuration
tmdb:
  max_pages: 500          # Maximum pages to fetch (500 pages = 10,000 movies)
  movies_per_page: 20     # Movies per page (TMDB default)
  rate_limit_delay: 0.1  # Delay between requests in seconds

# OMDb API Configuration
omdb:
  max_enrichments: 1000   # Maximum movies to enrich with OMDb data
  rate_limit_delay: 0.1   # Delay between requests in seconds

# Scraping Configuration
scraping:
  max_movies: 1000         # Maximum movies to scrape ratings for
  metacritic:
    rate_limit_delay: 1.0 # Delay between Metacritic requests
  rotten_tomatoes:
    rate_limit_delay: 2.0 # Delay between Rotten Tomatoes requests

# Data Processing
data_processing:
  save_intermediate: true  # Save data after each step
  batch_size: 100         # Process movies in batches
  retry_failed: true      # Retry failed requests
  max_retries: 3          # Maximum retry attempts

# Output Configuration
output:
  data_directory: "data/raw"
  file_prefix: "tmdb_top_rated"
  include_timestamp: true
  compression: false      # Set to true for large datasets
